/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/institutions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Institutions */
        get: operations["list_institutions_institutions_get"];
        put?: never;
        /** Create Institution */
        post: operations["create_institution_institutions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/institutions/{institution_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Institution */
        get: operations["get_institution_institutions__institution_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/taxonomy/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Categories */
        get: operations["list_categories_taxonomy_categories_get"];
        put?: never;
        /** Create Category */
        post: operations["create_category_taxonomy_categories_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/taxonomy/categories/{category_id}/terms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Term */
        post: operations["add_term_taxonomy_categories__category_id__terms_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/taxonomy/terms/{term_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Term */
        delete: operations["delete_term_taxonomy_terms__term_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Report */
        post: operations["upload_report_reports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/{report_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Report */
        get: operations["get_report_reports__report_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/{report_id}/reprocess": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reprocess Report
         * @description Re-run scoring — useful after editing the taxonomy.
         */
        post: operations["reprocess_report_reports__report_id__reprocess_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/{report_id}/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Evidence */
        get: operations["get_evidence_reports__report_id__evidence_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scores/reports/{report_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Report Score */
        get: operations["get_report_score_scores_reports__report_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scores/institutions/{institution_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Institution Score */
        get: operations["get_institution_score_scores_institutions__institution_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scores/rankings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Rankings
         * @description Full leaderboard across every institution with at least one scored report.
         */
        get: operations["get_rankings_scores_rankings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Meta */
        get: operations["get_meta_dashboard_meta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard/leaderboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Leaderboard */
        get: operations["get_leaderboard_dashboard_leaderboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard/institutions/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Institution Detail */
        get: operations["get_institution_detail_dashboard_institutions__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard/coverage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Coverage */
        get: operations["get_coverage_dashboard_coverage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Evidence */
        get: operations["get_evidence_dashboard_evidence_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard/evidence/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Evidence Review */
        post: operations["post_evidence_review_dashboard_evidence_review_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard/evidence/precision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Precision */
        get: operations["get_precision_dashboard_evidence_precision_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard/pdf/{report_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Pdf */
        get: operations["get_pdf_dashboard_pdf__report_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard/sensitivity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Sensitivity */
        get: operations["get_sensitivity_dashboard_sensitivity_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard/taxonomy/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tv Versions */
        get: operations["list_tv_versions_dashboard_taxonomy_versions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard/taxonomy/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Current Taxonomy */
        get: operations["get_current_taxonomy_dashboard_taxonomy_current_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard/methodology": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Methodology */
        get: operations["get_methodology_dashboard_methodology_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard/benchmark/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Benchmark Status
         * @description Session 7 stub: no benchmark data imported yet. The UI should render
         *     the empty-state 'upload a CSV to compare' prompt — NOT an error.
         */
        get: operations["benchmark_status_dashboard_benchmark_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard/benchmark/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Benchmark Upload */
        post: operations["benchmark_upload_dashboard_benchmark_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard/export/leaderboard.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Leaderboard */
        get: operations["export_leaderboard_dashboard_export_leaderboard_csv_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_upload_report_reports_post */
        Body_upload_report_reports_post: {
            /** Institution Id */
            institution_id: number;
            /** Fiscal Year */
            fiscal_year: number;
            /**
             * Language
             * @default en
             */
            language: string;
            /** File */
            file: string;
        };
        /** CategoryCreate */
        CategoryCreate: {
            /** Name */
            name: string;
            /** Pillar */
            pillar: string;
            /**
             * Weight
             * @default 1
             */
            weight: number;
        };
        /** CategoryOut */
        CategoryOut: {
            /** Name */
            name: string;
            /** Pillar */
            pillar: string;
            /**
             * Weight
             * @default 1
             */
            weight: number;
            /** Id */
            id: number;
            /**
             * Terms
             * @default []
             */
            terms: components["schemas"]["TermOut"][];
        };
        /** CategoryScoreOut */
        CategoryScoreOut: {
            /** Category Id */
            category_id: number;
            /** Category Name */
            category_name: string;
            /** Raw Weighted Count */
            raw_weighted_count: number;
            /** Density Per 1000 Words */
            density_per_1000_words: number;
        };
        /** CoverageCell */
        CoverageCell: {
            /** Status */
            status: string;
            /** Reason */
            reason: string;
            /** Source */
            source: string | null;
            /** Sha256 Prefix */
            sha256_prefix: string | null;
            /** Source Url */
            source_url: string | null;
        };
        /** CoverageOut */
        CoverageOut: {
            meta: components["schemas"]["LeaderboardMeta"];
            /** Fiscal Years */
            fiscal_years: number[];
            /** Rows */
            rows: components["schemas"]["CoverageRow"][];
            /** Unscored Reasons */
            unscored_reasons: {
                [key: string]: number;
            };
        };
        /** CoverageRow */
        CoverageRow: {
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Sector */
            sector: string;
            /** Cells */
            cells: {
                [key: string]: components["schemas"]["CoverageCell"];
            };
            /** Years Covered */
            years_covered: number[];
        };
        /** EvidenceOut */
        EvidenceOut: {
            meta: components["schemas"]["LeaderboardMeta"];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Rows */
            rows: components["schemas"]["EvidenceRow"][];
        };
        /** EvidenceRow */
        EvidenceRow: {
            /** Evidence Id */
            evidence_id: number;
            /** Report Id */
            report_id: number;
            /** Institution Slug */
            institution_slug: string;
            /** Institution Name */
            institution_name: string;
            /** Fiscal Year */
            fiscal_year: number;
            /** Pillar */
            pillar: string;
            /** Category */
            category: string;
            /** Term Phrase */
            term_phrase: string;
            /** Page Number */
            page_number: number;
            /** Sentence Text */
            sentence_text: string;
            /** Reviewed */
            reviewed: boolean;
            /** Reviewer */
            reviewer: string | null;
            /** Reviewer Verdict */
            reviewer_verdict: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InstitutionCreate */
        InstitutionCreate: {
            /** Name */
            name: string;
            /** Country */
            country: string;
            /**
             * Sector
             * @default banking
             */
            sector: string;
        };
        /** InstitutionDetail */
        InstitutionDetail: {
            /** Institution Id */
            institution_id: number;
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Country */
            country: string;
            /** Sector */
            sector: string;
            /** Industry */
            industry: string | null;
            /** Ticker */
            ticker: string | null;
            /** Market Cap Usd */
            market_cap_usd: number | null;
            /** Market Cap Date */
            market_cap_date: string | null;
            /** Data Quality Flag */
            data_quality_flag: string;
            /** Data Quality Reason */
            data_quality_reason: string;
            /** Years Covered */
            years_covered: number[];
            /** Reports */
            reports: components["schemas"]["ReportRow"][];
            /** Category Breakdown */
            category_breakdown: {
                [key: string]: {
                    [key: string]: number;
                };
            };
        };
        /** InstitutionOut */
        InstitutionOut: {
            /** Name */
            name: string;
            /** Country */
            country: string;
            /**
             * Sector
             * @default banking
             */
            sector: string;
            /** Id */
            id: number;
        };
        /** InstitutionRankingOut */
        InstitutionRankingOut: {
            /** Institution Id */
            institution_id: number;
            /** Institution Name */
            institution_name: string;
            /** Country */
            country: string;
            /** Institution Score */
            institution_score: number;
            /** Years Scored */
            years_scored: number;
            /** Pillar Breakdown */
            pillar_breakdown: {
                [key: string]: number;
            };
            /** Category Breakdown */
            category_breakdown: components["schemas"]["CategoryScoreOut"][];
        };
        /** LeaderboardMeta */
        LeaderboardMeta: {
            /** Taxonomy Version */
            taxonomy_version: string;
            /** Pipeline Version */
            pipeline_version: string;
            /** Data Snapshot Date */
            data_snapshot_date: string;
            /** Scored Institutions */
            scored_institutions: number;
            /** Active Institutions */
            active_institutions: number;
            /** Scored Reports */
            scored_reports: number;
        };
        /** LeaderboardOut */
        LeaderboardOut: {
            meta: components["schemas"]["LeaderboardMeta"];
            /** Rows */
            rows: components["schemas"]["LeaderboardRow"][];
        };
        /** LeaderboardRow */
        LeaderboardRow: {
            /** Institution Id */
            institution_id: number;
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Country */
            country: string;
            /** Sector */
            sector: string;
            /** Industry */
            industry: string | null;
            /** Rank Overall */
            rank_overall: number;
            /** Rank Within Sector */
            rank_within_sector: number;
            /** Mean Composite */
            mean_composite: number;
            /** Env */
            env: number;
            /** Soc */
            soc: number;
            /** Gov */
            gov: number;
            /** Years Covered */
            years_covered: number[];
            /** Data Quality Flag */
            data_quality_flag: string;
            /** Data Quality Reason */
            data_quality_reason: string;
        };
        /** MatchEvidenceOut */
        MatchEvidenceOut: {
            /** Page Number */
            page_number: number;
            /** Sentence Text */
            sentence_text: string;
            /** Term Phrase */
            term_phrase: string;
        };
        /** PrecisionCell */
        PrecisionCell: {
            /** Term Or Category */
            term_or_category: string;
            /** Reviewed */
            reviewed: number;
            /** Valid */
            valid: number;
            /** False Positive */
            false_positive: number;
            /** Unsure */
            unsure: number;
            /** Precision Point */
            precision_point: number | null;
        };
        /** ReportOut */
        ReportOut: {
            /** Id */
            id: number;
            /** Institution Id */
            institution_id: number;
            /** Fiscal Year */
            fiscal_year: number;
            /** Language */
            language: string;
            /** Status */
            status: string;
            /** Total Word Count */
            total_word_count: number;
            /** Page Count */
            page_count: number;
            /** Error Message */
            error_message?: string | null;
        };
        /** ReportRow */
        ReportRow: {
            /** Report Id */
            report_id: number;
            /** Fiscal Year */
            fiscal_year: number;
            /** Source */
            source: string;
            /** Source Url */
            source_url: string;
            /** Retrieved At */
            retrieved_at: string;
            /** Sha256 Prefix */
            sha256_prefix: string;
            /** Review Status */
            review_status: string;
            /** Processing Review Status */
            processing_review_status: string;
            /** Page Count */
            page_count: number;
            /** Composite Score */
            composite_score: number;
            /** Env */
            env: number;
            /** Soc */
            soc: number;
            /** Gov */
            gov: number;
        };
        /** ReportScoreOut */
        ReportScoreOut: {
            /** Report Id */
            report_id: number;
            /** Fiscal Year */
            fiscal_year: number;
            /** Composite Score */
            composite_score: number;
            /** Pillar Scores */
            pillar_scores: {
                [key: string]: number;
            };
            /** Category Scores */
            category_scores: components["schemas"]["CategoryScoreOut"][];
        };
        /** ReviewSubmit */
        ReviewSubmit: {
            /** Evidence Id */
            evidence_id: number;
            /** Reviewer */
            reviewer: string;
            /** Verdict */
            verdict: string;
        };
        /** SensitivityInstitutionRow */
        SensitivityInstitutionRow: {
            /** Slug */
            slug: string;
            /** Sector */
            sector: string;
            /** Years Covered */
            years_covered: number;
            /** Baseline Rank */
            baseline_rank: number;
            /** Jitter Median Rank */
            jitter_median_rank: number;
            /** Jitter P5 Rank */
            jitter_p5_rank: number;
            /** Jitter P95 Rank */
            jitter_p95_rank: number;
            /** Jitter Interval Width */
            jitter_interval_width: number;
            /** Equal Weights Rank */
            equal_weights_rank: number;
            /** Toc Off Rank */
            toc_off_rank: number;
            /** Repeat Off Rank */
            repeat_off_rank: number;
            /** All Mode Rank */
            all_mode_rank: number;
            /** Flag Single Year High Volatility */
            flag_single_year_high_volatility: boolean;
        };
        /** SensitivityOut */
        SensitivityOut: {
            meta: components["schemas"]["LeaderboardMeta"];
            /** Kendall Fin Median */
            kendall_fin_median: number;
            /** Kendall Fin P5 */
            kendall_fin_p5: number;
            /** Kendall Fin P95 */
            kendall_fin_p95: number;
            /** Kendall Non Fin Median */
            kendall_non_fin_median: number;
            /** Kendall Non Fin P5 */
            kendall_non_fin_p5: number;
            /** Kendall Non Fin P95 */
            kendall_non_fin_p95: number;
            /** Equal Spearman Fin */
            equal_spearman_fin: number;
            /** Equal Spearman Non Fin */
            equal_spearman_non_fin: number;
            /** Switch Summary */
            switch_summary: {
                [key: string]: {
                    [key: string]: number;
                };
            };
            /** Rows */
            rows: components["schemas"]["SensitivityInstitutionRow"][];
            /** Summary Markdown */
            summary_markdown: string;
        };
        /** TaxonomyCategoryView */
        TaxonomyCategoryView: {
            /** Category Id */
            category_id: number;
            /** Name */
            name: string;
            /** Pillar */
            pillar: string;
            /** Weight */
            weight: number;
            /** Sourcing Note */
            sourcing_note: string;
            /** Terms */
            terms: components["schemas"]["TaxonomyTermView"][];
        };
        /** TaxonomyTermView */
        TaxonomyTermView: {
            /** Term Id */
            term_id: number;
            /** Phrase */
            phrase: string;
            /** Weight */
            weight: number;
            /** Lemma Based */
            lemma_based: boolean;
        };
        /** TaxonomyVersionView */
        TaxonomyVersionView: {
            /** Hash */
            hash: string;
            /** Created At */
            created_at: string;
            /** Note */
            note: string | null;
            /** Categories */
            categories: components["schemas"]["TaxonomyCategoryView"][];
        };
        /** TermCreate */
        TermCreate: {
            /** Phrase */
            phrase: string;
            /**
             * Weight
             * @default 1
             */
            weight: number;
            /**
             * Lemma Based
             * @default true
             */
            lemma_based: boolean;
        };
        /** TermOut */
        TermOut: {
            /** Phrase */
            phrase: string;
            /**
             * Weight
             * @default 1
             */
            weight: number;
            /**
             * Lemma Based
             * @default true
             */
            lemma_based: boolean;
            /** Id */
            id: number;
            /** Category Id */
            category_id: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_institutions_institutions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstitutionOut"][];
                };
            };
        };
    };
    create_institution_institutions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InstitutionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstitutionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_institution_institutions__institution_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                institution_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstitutionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_categories_taxonomy_categories_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryOut"][];
                };
            };
        };
    };
    create_category_taxonomy_categories_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_term_taxonomy_categories__category_id__terms_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                category_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TermCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TermOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_term_taxonomy_terms__term_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                term_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_report_reports_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_report_reports_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_report_reports__report_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reprocess_report_reports__report_id__reprocess_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_evidence_reports__report_id__evidence_get: {
        parameters: {
            query?: {
                term_id?: number | null;
            };
            header?: never;
            path: {
                report_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchEvidenceOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_report_score_scores_reports__report_id__get: {
        parameters: {
            query?: {
                /** @description Defaults to the latest version */
                taxonomy_version_id?: number | null;
            };
            header?: never;
            path: {
                report_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportScoreOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_institution_score_scores_institutions__institution_id__get: {
        parameters: {
            query?: {
                recency_weighted?: boolean;
                taxonomy_version_id?: number | null;
            };
            header?: never;
            path: {
                institution_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstitutionRankingOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_rankings_scores_rankings_get: {
        parameters: {
            query?: {
                recency_weighted?: boolean;
                taxonomy_version_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstitutionRankingOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_meta_dashboard_meta_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeaderboardMeta"];
                };
            };
        };
    };
    get_leaderboard_dashboard_leaderboard_get: {
        parameters: {
            query?: {
                /** @description All | Financial | Non-financial | <industry> */
                cohort?: string;
                country?: string | null;
                /** @description If set, show that single-year composite instead of mean */
                fy?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeaderboardOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_institution_detail_dashboard_institutions__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstitutionDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_coverage_dashboard_coverage_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoverageOut"];
                };
            };
        };
    };
    get_evidence_dashboard_evidence_get: {
        parameters: {
            query?: {
                institution_slug?: string | null;
                fiscal_year?: number | null;
                pillar?: string | null;
                category?: string | null;
                term?: string | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_evidence_review_dashboard_evidence_review_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewSubmit"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_precision_dashboard_evidence_precision_get: {
        parameters: {
            query?: {
                /** @description term | category | pillar */
                group?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PrecisionCell"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_pdf_dashboard_pdf__report_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_sensitivity_dashboard_sensitivity_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SensitivityOut"];
                };
            };
        };
    };
    list_tv_versions_dashboard_taxonomy_versions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaxonomyVersionView"][];
                };
            };
        };
    };
    get_current_taxonomy_dashboard_taxonomy_current_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaxonomyVersionView"];
                };
            };
        };
    };
    get_methodology_dashboard_methodology_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    benchmark_status_dashboard_benchmark_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    benchmark_upload_dashboard_benchmark_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    export_leaderboard_dashboard_export_leaderboard_csv_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
