"""scope correction: active flag + superseded_by_id

Revision ID: 28b484556dce
Revises: c5b330c2f3f3
Create Date: 2026-10-02 19:23:46.916959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28b484556dce'
down_revision: Union[str, Sequence[str], None] = 'c5b330c2f3f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('institutions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=False,
                                      server_default=sa.true()))
        batch_op.create_index(batch_op.f('ix_institutions_active'), ['active'], unique=False)

    with op.batch_alter_table('source_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('superseded_by_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_source_documents_superseded_by_id'), ['superseded_by_id'], unique=False)
        batch_op.create_foreign_key('fk_source_documents_superseded_by_id',
                                    'source_documents', ['superseded_by_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('source_documents', schema=None) as batch_op:
        # WARNING: constraint name is None; this directive will fail as
        # rendered.  Add a name, or use a naming convention; see
        # https://alembic.sqlalchemy.org/en/latest/naming.html
        batch_op.drop_constraint('fk_source_documents_superseded_by_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_source_documents_superseded_by_id'))
        batch_op.drop_column('superseded_by_id')

    with op.batch_alter_table('institutions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_institutions_active'))
        batch_op.drop_column('active')

    # ### end Alembic commands ###
