"""v4_taxonomy_scoring_fields

Revision ID: 4dac1c5bae78
Revises: 4e21cde2a1f0
Create Date: 2026-10-10 09:19:24.038975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4dac1c5bae78'
down_revision: Union[str, Sequence[str], None] = '4e21cde2a1f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('institutions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sasb_industry', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_institutions_sasb_industry'), ['sasb_industry'], unique=False)

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('narrative_word_count', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('e_density', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('s_density', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('g_density', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('e_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('s_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('g_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('generic_density', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('addon_density', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('addon_rank', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('report_type', sa.String(), nullable=True))

    with op.batch_alter_table('terms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group', sa.String(), nullable=False, server_default='core'))
        batch_op.add_column(sa.Column('sasb_category_primary', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('sasb_category_secondary', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('terms', schema=None) as batch_op:
        batch_op.drop_column('sasb_category_secondary')
        batch_op.drop_column('sasb_category_primary')
        batch_op.drop_column('group')

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_column('report_type')
        batch_op.drop_column('addon_rank')
        batch_op.drop_column('addon_density')
        batch_op.drop_column('generic_density')
        batch_op.drop_column('g_score')
        batch_op.drop_column('s_score')
        batch_op.drop_column('e_score')
        batch_op.drop_column('g_density')
        batch_op.drop_column('s_density')
        batch_op.drop_column('e_density')
        batch_op.drop_column('narrative_word_count')

    with op.batch_alter_table('institutions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_institutions_sasb_industry'))
        batch_op.drop_column('sasb_industry')

    # ### end Alembic commands ###
