"""institution registry + provenance + taxonomy versioning

Revision ID: 91e1191ec654
Revises: cb82e3caed90
Create Date: 2026-09-30 12:40:09.874758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91e1191ec654'
down_revision: Union[str, Sequence[str], None] = 'cb82e3caed90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('taxonomy_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('taxonomy_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_taxonomy_versions_hash'), ['hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_taxonomy_versions_id'), ['id'], unique=False)

    op.create_table('crawl_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('outcome', sa.String(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('crawl_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crawl_log_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crawl_log_run_id'), ['run_id'], unique=False)

    op.create_table('gaps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Enum('not_found', 'blocked', 'robots_disallowed', 'year_mismatch', 'unreachable', 'other', name='gapreason'), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('tier_tried', sa.String(), nullable=True),
    sa.Column('next_action', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('institution_id', 'fiscal_year', name='uq_gap_inst_year')
    )
    with op.batch_alter_table('gaps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gaps_id'), ['id'], unique=False)

    op.create_table('source_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('report_type', sa.Enum('annual', 'integrated', 'sustainability', 'financial_statements', 'other', 'unknown', name='reporttype'), nullable=False),
    sa.Column('source', sa.Enum('crawler', 'wayback', 'manual', name='sourcetype'), nullable=False),
    sa.Column('source_url', sa.String(), nullable=False),
    sa.Column('final_url', sa.String(), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sha256', sa.String(), nullable=False),
    sa.Column('bytes', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('includes_financial_statements', sa.Boolean(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('review_status', sa.Enum('auto_ok', 'needs_review', 'rejected', name='reviewstatus'), nullable=False),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('source_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_source_documents_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_documents_sha256'), ['sha256'], unique=True)

    with op.batch_alter_table('category_scores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('taxonomy_version_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_category_scores_pipeline_version'), ['pipeline_version'], unique=False)
        batch_op.create_index(batch_op.f('ix_category_scores_taxonomy_version_id'), ['taxonomy_version_id'], unique=False)
        batch_op.create_index('ix_category_scores_versioning', ['report_id', 'taxonomy_version_id', 'pipeline_version'], unique=False)
        batch_op.create_foreign_key('fk_category_scores_taxonomy_version_id', 'taxonomy_versions', ['taxonomy_version_id'], ['id'])

    # Pre-create the enum types that get used in ADD COLUMN below. SQLite
    # ignores named enums (stores strings), so `.create(..., checkfirst=True)`
    # is a no-op there; on Postgres we need `CREATE TYPE … AS ENUM (…)` to
    # exist before any column references it. Session 9: Postgres migration.
    wave_enum = sa.Enum('financial', 'other', name='wave')
    inst_type_enum = sa.Enum('bank', 'insurer', 'investment_holding',
                             'leasing', 'other', name='institutiontype')
    wave_enum.create(op.get_bind(), checkfirst=True)
    inst_type_enum.create(op.get_bind(), checkfirst=True)

    with op.batch_alter_table('institutions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rank', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ticker', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('market_cap_usd', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('market_cap_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('industry', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('slug', sa.String(), nullable=True))
        # server_default so ADD COLUMN NOT NULL succeeds for any pre-existing
        # rows; loader overwrites with the real value.
        # Portable boolean default — `sa.false()` emits `FALSE` on Postgres
        # and `0` on SQLite, so this migration runs on both backends.
        batch_op.add_column(sa.Column('is_financial', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('wave', sa.Enum('financial', 'other', name='wave', create_type=False), nullable=False, server_default='other'))
        batch_op.add_column(sa.Column('institution_type', sa.Enum('bank', 'insurer', 'investment_holding', 'leasing', 'other', name='institutiontype', create_type=False), nullable=True))
        batch_op.create_index(batch_op.f('ix_institutions_industry'), ['industry'], unique=False)
        batch_op.create_index(batch_op.f('ix_institutions_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_institutions_ticker'), ['ticker'], unique=False)
        batch_op.create_index(batch_op.f('ix_institutions_wave'), ['wave'], unique=False)
        batch_op.create_unique_constraint('uq_institutions_rank', ['rank'])

    with op.batch_alter_table('match_evidence', schema=None) as batch_op:
        batch_op.add_column(sa.Column('taxonomy_version_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('pipeline_version', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_match_evidence_pipeline_version'), ['pipeline_version'], unique=False)
        batch_op.create_index(batch_op.f('ix_match_evidence_taxonomy_version_id'), ['taxonomy_version_id'], unique=False)
        batch_op.create_foreign_key('fk_match_evidence_taxonomy_version_id', 'taxonomy_versions', ['taxonomy_version_id'], ['id'])

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_document_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_reports_source_document_id'), ['source_document_id'], unique=False)
        batch_op.create_foreign_key('fk_reports_source_document_id', 'source_documents', ['source_document_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_constraint('fk_reports_source_document_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_reports_source_document_id'))
        batch_op.drop_column('source_document_id')

    with op.batch_alter_table('match_evidence', schema=None) as batch_op:
        batch_op.drop_constraint('fk_match_evidence_taxonomy_version_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_match_evidence_taxonomy_version_id'))
        batch_op.drop_index(batch_op.f('ix_match_evidence_pipeline_version'))
        batch_op.drop_column('pipeline_version')
        batch_op.drop_column('taxonomy_version_id')

    with op.batch_alter_table('institutions', schema=None) as batch_op:
        batch_op.drop_constraint('uq_institutions_rank', type_='unique')
        batch_op.drop_index(batch_op.f('ix_institutions_wave'))
        batch_op.drop_index(batch_op.f('ix_institutions_ticker'))
        batch_op.drop_index(batch_op.f('ix_institutions_slug'))
        batch_op.drop_index(batch_op.f('ix_institutions_industry'))
        batch_op.drop_column('institution_type')
        batch_op.drop_column('wave')
        batch_op.drop_column('is_financial')
        batch_op.drop_column('slug')
        batch_op.drop_column('industry')
        batch_op.drop_column('market_cap_date')
        batch_op.drop_column('market_cap_usd')
        batch_op.drop_column('ticker')
        batch_op.drop_column('rank')

    with op.batch_alter_table('category_scores', schema=None) as batch_op:
        batch_op.drop_constraint('fk_category_scores_taxonomy_version_id', type_='foreignkey')
        batch_op.drop_index('ix_category_scores_versioning')
        batch_op.drop_index(batch_op.f('ix_category_scores_taxonomy_version_id'))
        batch_op.drop_index(batch_op.f('ix_category_scores_pipeline_version'))
        batch_op.drop_column('taxonomy_version_id')

    with op.batch_alter_table('source_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_source_documents_sha256'))
        batch_op.drop_index(batch_op.f('ix_source_documents_id'))

    op.drop_table('source_documents')
    with op.batch_alter_table('gaps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gaps_id'))

    op.drop_table('gaps')
    with op.batch_alter_table('crawl_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crawl_log_run_id'))
        batch_op.drop_index(batch_op.f('ix_crawl_log_id'))

    op.drop_table('crawl_log')
    with op.batch_alter_table('taxonomy_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_taxonomy_versions_id'))
        batch_op.drop_index(batch_op.f('ix_taxonomy_versions_hash'))

    op.drop_table('taxonomy_versions')
    # ### end Alembic commands ###
