"""add targeted_search to SourceType enum

Revision ID: 93a446552d20
Revises: 8051f61a00ab
Create Date: 2026-10-01 18:37:18.733400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93a446552d20'
down_revision: Union[str, Sequence[str], None] = '8051f61a00ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('source_documents', schema=None) as batch_op:
        batch_op.alter_column('source',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.Enum('crawler', 'exchange', 'wayback', 'manual', 'targeted_search', name='sourcetype'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('source_documents', schema=None) as batch_op:
        batch_op.alter_column('source',
               existing_type=sa.Enum('crawler', 'exchange', 'wayback', 'manual', 'targeted_search', name='sourcetype'),
               type_=sa.VARCHAR(length=8),
               existing_nullable=False)

    # ### end Alembic commands ###
