"""add runs table

Revision ID: aa84e886807c
Revises: 028d3c041f16
Create Date: 2026-10-03 01:54:57.610524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa84e886807c'
down_revision: Union[str, Sequence[str], None] = '028d3c041f16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('git_commit', sa.String(), nullable=False),
    sa.Column('taxonomy_version', sa.String(), nullable=False),
    sa.Column('pipeline_version', sa.String(), nullable=False),
    sa.Column('config_hash', sa.String(), nullable=False),
    sa.Column('manifest_hash', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_runs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_runs_kind'), ['kind'], unique=False)

    op.create_table('match_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('reviewer', sa.String(), nullable=False),
    sa.Column('verdict', sa.String(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['match_evidence.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('evidence_id', name='uq_match_reviews_evidence_id')
    )
    with op.batch_alter_table('match_reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_match_reviews_evidence_id'), ['evidence_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_match_reviews_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match_reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_match_reviews_id'))
        batch_op.drop_index(batch_op.f('ix_match_reviews_evidence_id'))

    op.drop_table('match_reviews')
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_runs_kind'))
        batch_op.drop_index(batch_op.f('ix_runs_id'))

    op.drop_table('runs')
    # ### end Alembic commands ###
