"""add 'exchange' to SourceType enum

Revision ID: abef1cb3d9d1
Revises: 91e1191ec654
Create Date: 2026-09-30 13:32:22.560833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abef1cb3d9d1'
down_revision: Union[str, Sequence[str], None] = '91e1191ec654'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('source_documents', schema=None) as batch_op:
        batch_op.alter_column('source',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.Enum('crawler', 'exchange', 'wayback', 'manual', name='sourcetype'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('source_documents', schema=None) as batch_op:
        batch_op.alter_column('source',
               existing_type=sa.Enum('crawler', 'exchange', 'wayback', 'manual', name='sourcetype'),
               type_=sa.VARCHAR(length=7),
               existing_nullable=False)

    # ### end Alembic commands ###
