"""add report processing audit fields

Revision ID: c5b330c2f3f3
Revises: 93a446552d20
Create Date: 2026-10-02 12:34:34.593037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5b330c2f3f3'
down_revision: Union[str, Sequence[str], None] = '93a446552d20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extract_seconds', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('segment_seconds', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('match_seconds', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_seconds', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('ocr_page_count', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('ocr_page_ratio', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('repeated_lines_removed', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('excluded_contents_pages', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('pages_mostly_arabic', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('financial_statements_start_page', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('financial_statements_excluded_pages', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('matches_count', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('all_mode_extra_matches', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('composite_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('processing_review_status', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('processing_review_reason', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_column('processing_review_reason')
        batch_op.drop_column('processing_review_status')
        batch_op.drop_column('composite_score')
        batch_op.drop_column('all_mode_extra_matches')
        batch_op.drop_column('matches_count')
        batch_op.drop_column('financial_statements_excluded_pages')
        batch_op.drop_column('financial_statements_start_page')
        batch_op.drop_column('pages_mostly_arabic')
        batch_op.drop_column('excluded_contents_pages')
        batch_op.drop_column('repeated_lines_removed')
        batch_op.drop_column('ocr_page_ratio')
        batch_op.drop_column('ocr_page_count')
        batch_op.drop_column('total_seconds')
        batch_op.drop_column('match_seconds')
        batch_op.drop_column('segment_seconds')
        batch_op.drop_column('extract_seconds')

    # ### end Alembic commands ###
