"""baseline schema

Revision ID: cb82e3caed90
Revises: 
Create Date: 2026-09-30 12:05:17.293818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb82e3caed90'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('pillar', sa.String(), nullable=False),
    sa.Column('weight', sa.Double(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_id'), ['id'], unique=False)

    op.create_table('institutions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('sector', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('institutions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_institutions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_institutions_name'), ['name'], unique=False)

    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('total_word_count', sa.Integer(), nullable=False),
    sa.Column('latin_word_count', sa.Integer(), nullable=False),
    sa.Column('arabic_word_count', sa.Integer(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('uploaded', 'processing', 'scored', 'error', name='reportstatus'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('taxonomy_version', sa.String(), nullable=True),
    sa.Column('pipeline_version', sa.String(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_id'), ['id'], unique=False)

    op.create_table('terms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('phrase', sa.String(), nullable=False),
    sa.Column('weight', sa.Double(), nullable=False),
    sa.Column('lemma_based', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('terms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_terms_id'), ['id'], unique=False)

    op.create_table('category_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('raw_weighted_count', sa.Double(), nullable=False),
    sa.Column('density_per_1000_words', sa.Double(), nullable=False),
    sa.Column('taxonomy_version', sa.String(), nullable=True),
    sa.Column('pipeline_version', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('category_scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_category_scores_id'), ['id'], unique=False)

    op.create_table('match_evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('term_id', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('sentence_text', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('match_evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_match_evidence_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match_evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_match_evidence_id'))

    op.drop_table('match_evidence')
    with op.batch_alter_table('category_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_category_scores_id'))

    op.drop_table('category_scores')
    with op.batch_alter_table('terms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_terms_id'))

    op.drop_table('terms')
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_id'))

    op.drop_table('reports')
    with op.batch_alter_table('institutions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_institutions_name'))
        batch_op.drop_index(batch_op.f('ix_institutions_id'))

    op.drop_table('institutions')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_id'))

    op.drop_table('categories')
    # ### end Alembic commands ###
